# Generated by Django 2.2 on 2022-01-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_servicesitem_servicesitemtranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='references', verbose_name='Görsel')),
            ],
            options={
                'verbose_name': 'Referans Görseli',
                'verbose_name_plural': 'Referans Görseli',
            },
        ),
    ]
